world:
    data_file: world_generator/data/dummy.json
    detail_plots: false 
    capture_video: false
    save_file_name: simulation
    victims:
        count: 100
        t_max: '10:00:00'
        t_min: '05:00:00'
        t_var: '02:00:00'
        pi_detected: t >= obj.t_detected
        pi_rescued: t >= obj.rescued
gui:
    verbose: 2
    save_gif: false
    optimizer_types: [random, greedy, brute_force, ga]
    preprocessing_types: [closest, shortest_path]
    analysis_types: [heatmap, 
                     victim,
                     utility, 
                     energy, 
                     tasks, 
                     area,
                     distance]
    charger_types: [static, dynamic]
mission:
    t_end: '15:00:00'
    mcdm: MCDM_weights.mat
    PI_model: PI_model.fis
    prediction_errors: false
    coordination_radius: 5
    tasks:
        map:
            type: map
            pi_init: ismember(node, frontier) && ~ismember(node, task_nodes)
            pi_complete: ~ismember(node, frontier)
        search:
            type: search
            pi_init: PI >= 0.5
            pi_complete: ismember(node, robot.detector.measurements.nodes)
    charger:
        id: charger
        q_init: [1,1]
        max_step: 0.5
        speed: 0.1
        color: white
        policy: 
            optimizer: dynamic
            control_horizon: 10
            task_proximity: 2
    robots:
        ugv:
            count: 1
            q_init: [[1,1], [1,1]]
        uav: 
            count: 1
            q_init: [[1,1]]
        crawler:
            count: 1
            q_init: [[1,1]]