world:
    data_file: world_generator/data/dummy.json
    distance_mode: 3d
    victims:
        count: 50
        destruct_thresh: 0.3
        t_avg: 01:00:00

sensors:
    remote_sensor:
        t_s: 05:00
        d_energy: 0
        features: [victim]
        remote_sensing: true
        color: magenta
    
    visible_sensor:
        t_s: 01:00
        d_energy: 0
        features: [terrain, destruction, population]
        remote_sensing: false
        color: green

mission:
    t_end: 01:00:00
    map_features: [terrain]
    robots:
        ugv:
            count: 1
            p_init: [[25, 25]]
            id: ugv
            max_step: 1
            height: 1
            speed: 3
            crit_energy: 0
            energy_per_m: 0.01
            remote_range: 10
            visible_range: 50
            PI_model: PI_model.fis
            color: black
        
        uav:
            count: 0
            p_init: [[20, 375]]
            id: uav
            max_step: 100
            height: inf
            speed: 5
            crit_energy: 0
            energy_per_m: 0.1
            remote_range: 20
            visible_range: 75
            PI_model: PI_model.fis
            color: white
   
tasks:
    explore:
        pi: visible_sensor
        spawn: 0
        kill:  0.7
    search:
        pi: remote_sensor
        spawn: 0.5
        kill: 0.9

