world:
    data_file: ../world_generator/data/dummy.json
    detail_plots: false 
    capture_video: false
    save_file_name: simulation
    victims:
        count: 100
        t_max: '10:00:00'
        t_min: '05:00:00'
        t_var: '02:00:00'
        pi_detected: t >= obj.t_detected
        pi_rescued: t >= obj.rescued
gui:
    verbose: 2
    save_gif: false
    optimizer_types: [random, greedy, brute_force, ga]
    preprocessing_types: [closest, shortest_path]
    analysis_types: [heatmap, 
                     victim,
                     utility, 
                     energy, 
                     tasks, 
                     area,
                     distance]
    charger_types: [static, dynamic]
mission:
    t_end: '07:00:00'
    mcdm: MCDM_weights.mat
    PI_model: PI_model.fis
    prediction_errors: false
    coordination_radius: 2
    tasks:
        map:
            type: map
            pi_init: ismember(node, frontier) && ~ismember(node, task_nodes)
            pi_complete: ~ismember(node, frontier)
        search:
            type: search
            pi_init: PI >= 0.5
            pi_complete: ismember(node, robot.detector.measurements.nodes)
    charger:
        id: charger
        q_init: [1,1]
        max_step: 0.5
        speed: 1
        color: white
        policy: 
            optimizer: dynamic
            control_horizon: 1
            task_proximity: 10
    robots:
        ugv:
            count: 2
            q_init: [[1,1], [1,1]]
            max_step: 1
            height: 1
            speed: 3
            crit_energy: 0
            energy_per_m: 0.1
            charge_s: '03:00'
            color: black
            policy:
                preprocessing: closest
                num_tasks: 25
                optimizer: greedy
                control_horizon: 1
                prediction_horizon: 10
            capabilities:
                detector:
                    type: search
                    capability: 1
                    model: search_capability.mat
                    t_s: '10:00'
                    d_energy: 5
                    features: [victim]
                    max_range: 3
                    arc: 360
                    angles: [0]
                mapper:
                    type: map
                    capability: 1
                    model: map_capability.fis
                    t_s: '01:00'
                    d_energy: 1
                    features: [terrain, destruction, population]
                    max_range: 7
                    arc: 90
                    angles: [0, 45, 90, 135, 180, 225, 270, 315]
  