world:
    data_file: world_generator/data/dummy.json
    distance_mode: 3d
    victims:
        count: 50
        destruct_thresh: 0.3
        t_avg: 01:00:00

sensors:
    remote_sensor:
        t_s: 00:00
        d_energy: 0.01
        features: [victim]
        remote_sensing: true
        color: magenta
    
    visible_sensor:
        t_s: 00:00
        d_energy: 0.01
        features: [terrain, destruction, population]
        remote_sensing: false
        color: green

mission:
    t_end: 01:00:00
    map_features: [terrain]
    robots:
        ugv:
            count: 1
            p_init: [[10, 450]]
            id: ugv
            max_step: 1
            height: 1
            speed: 3
            crit_energy: 0
            energy_per_m: 0.01
            remote_range: 10
            visible_range: 50
            PI_model: PI_model.fis
            color: black
        
        uav:
            count: 0
            p_init: [[20, 450]]
            id: uav
            max_step: 100
            height: 10
            speed: 5
            crit_energy: 0
            energy_per_m: 0.1
            remote_range: 20
            visible_range: 75
            PI_model: PI_model.fis
            color: white
   
tasks:
    explore:
        pi: visible_sensor
        spawn_thresh: 0.8
        kill_thresh: 0.2

