world:
    data_file: world_generator/data/dummy.json
    capture_video: false
    victims:
        count: 100
        t_max: '10:00:00'
        t_min: '05:00:00'
        t_var: '02:00:00'
gui:
    verbose: 2
    save_gif: false
    optimizer_types: [random, greedy, brute_force, ga]
    preprocessing_types: [closest, shortest_path]
    analysis_types: [heatmap, 
                     victim,
                     utility, 
                     energy, 
                     tasks, 
                     area,
                     distance]
    charger_types: [static, center_of_mass]
mission:
    t_end: '15:00:00'
    PI_model: PI_model.fis
    prediction_errors: false
    coordination_radius: 3
    q_init: [1,1]
    tasks:
        map:
            type: map
            pi_init: ismember(node, frontier) && ~ismember(node, task_nodes)
            pi_complete: ~ismember(node, frontier)
        search:
            type: search
            pi_init: PI >= 0.6
            pi_complete: ismember(node, robot.detector.measurements.nodes)
    mcdm:
        t: 0.4
        m: 0.5
        s: 0.7
        mt: 0.6
        st: 0.9
        ms: 0.8
        mst: 1
    charger:
        id: charger
        max_step: 0.5
        speed: 0.1
        color: white
        policy: 
            optimizer: center_of_mass
            control_horizon: 100
            task_proximity: 3
    robots:
        ugv:
            count: 1
        uav: 
            count: 1
        crawler:
            count: 1